### ISSUE TITLE
Automate rebuilds with Travis CI

### ISSUE THREAD

**Issue by namurphy** [PlasmaPy/plasmapy.github.io#3]
It would probably be helpful if we could [automate Nikola rebuilds with Travis CI](https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html).  I started to set this up, but unfortunately I was not able to get this to work.  If anyone with more (or any!) experience with Travis CI would like to take a look at this, please do!

**Comment by namurphy** [comment]
This is the error I got when I tried to trigger a rebuild:
```
0.01s$ openssl aes-256-cbc -K $encrypted_5efde3fde6ee_key -iv $encrypted_5efde3fde6ee_iv -in
id_rsa.enc -out id_rsa -d

iv undefined

The command "openssl aes-256-cbc -K $encrypted_5efde3fde6ee_key -iv $encrypted_5efde3fde6ee_iv -in id_rsa.enc -out id_rsa -d" failed and exited with 1 during .

Your build has been stopped.
```

Looks like a problem with RSA encryption.  I'll try to come back to this after I get some sleep. :smiley_cat:

**Comment by sinoroc** [comment]
(found you there: http://up-for-grabs.net)

This tutorial from Nikola seems unnecessary complicated. It might not have been the case when you started this effort, but Travis CI offers a much better way to solve this:
https://docs.travis-ci.com/user/deployment/pages/

Something similar to this should get you there:

```yaml
language: 'python'
install:
  - 'pip install --requirement requirements.txt'
script:
  - 'nikola build'
deploy:
  - provider: 'pages'
    skip_cleanup: true
    target-branch: 'master'
    on:
      branch: 'src'
    local-dir: 'output'
    github_token:
      secure: "..."
```

Have not actually tested this (might do later) and can't be certain it will work for sure, but hope this helps anyway.
